# Generated by Django 5.1.15 on 2026-06-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('ingredients_text', models.TextField(blank=True)),
                ('off_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_product',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('certifying_body', models.CharField(choices=[('IFANCA', 'IFANCA'), ('HMS', 'HMS (Halal Monitoring Services)'), ('HFSAA', 'HFSAA (Halal Food Standards Alliance of America)'), ('JAKIM', 'JAKIM'), ('OTHER', 'Other')], max_length=10)),
                ('certified', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_certification',
                'unique_together': {('brand', 'certifying_body')},
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('e_number', models.CharField(blank=True, max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('haram', 'Haram'), ('halal', 'Halal'), ('doubtful', 'Doubtful')], max_length=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_ingredient',
                'indexes': [models.Index(fields=['category'], name='products_in_categor_48b290_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='products.product')),
            ],
            options={
                'db_table': 'products_productingredient',
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductIngredient', to='products.ingredient'),
        ),
    ]
